apiVersion: v1
kind: Service
metadata:
  name: service-registry
  labels:
    app.kubernetes.io/name: service-registry
    app.kubernetes.io/version: "0.1.0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: service-registry
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
